AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  
require: rubocop-rails

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

